name: Deploy to Huawei Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install rsync on server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} root@${{ secrets.SERVER_HOST }} << 'EOF'
          # 检查并安装 rsync
          if ! command -v rsync &> /dev/null; then
            if command -v apt-get &> /dev/null; then
              apt-get update && apt-get install -y rsync
            elif command -v yum &> /dev/null; then
              yum install -y rsync
            elif command -v dnf &> /dev/null; then
              dnf install -y rsync
            else
              echo "Package manager not found. Please install rsync manually."
              exit 1
            fi
          fi
        EOF

    - name: Copy files to server
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" ./ root@${{ secrets.SERVER_HOST }}:/var/www/screen_scan_ocr

    - name: Create .env file on server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} root@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/www/screen_scan_ocr
          cat > .env << EOL
          OCR_KEY=${{ secrets.OCR_KEY }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          NODE_ENV=production
          NUXT_HOST=0.0.0.0
          NUXT_PORT=3000
          EOL
        EOF

    - name: Build and restart Docker on server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} root@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/www/screen_scan_ocr
          docker-compose down || true
          docker-compose build --no-cache
          docker-compose up -d
        EOF